name: 🐛 Bug Report
description: Signaler un bug ou un comportement inattendu
title: "[BUG] - "
labels: [bug]
assignees:
  - koydas

body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir ce rapport de bug de manière claire et concise 🙏

  - type: input
    id: environment
    attributes:
      label: Environnement
      description: OS, navigateur ou runtime, version, etc.
      placeholder: ex. Windows 11, Node.js v18, Chrome 123
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du problème
      placeholder: Décris le bug rencontré
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      placeholder: Qu'est-ce que tu t'attendais à voir ?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Console
      placeholder: Copie les logs ici
      render: shell
    validations:
      required: false
