name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] - "
labels: [bug]
assignees:
  - koydas

body:
  - type: markdown
    attributes:
      value: |
        Please fill out this bug report clearly and concisely 🙏

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser or runtime, version, etc.
      placeholder: e.g. Windows 11, Node.js v18, Chrome 123
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue description
      placeholder: Describe the bug you encountered
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the concrete effects (e.g., blocked flows, data risk, performance degradation).
      placeholder: e.g., "Checkout blocked for all mobile users; 500 error after submitting payment."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to see?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Console
      placeholder: Paste any relevant logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Provide measurable, binary conditions to mark this issue complete.
      value: |-
        - [ ] Reproduction steps succeed without errors across supported environments
        - [ ] Related logs show no unhandled exceptions for this path
        - [ ] Regression coverage added for the fixed path
    validations:
      required: true
