name: ✨ Feature Request
description: Propose a new feature in a few quick steps
title: "[FEATURE] - "
labels: [enhancement]
assignees:
  - koydas

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please outline the need and your proposed solution. 🙌

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What need or pain point does this address?
      placeholder: e.g. Night users find the interface too bright
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How significant is this change?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the approach or expected behavior.
      placeholder: e.g. Add a button to enable a persistent dark theme
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Constraints or notes
      description: Dependencies, quick alternatives, or useful links (optional).
    validations:
      required: false
