name: ✨ Feature Request
description: Suggest an idea or improvement
title: "[FEATURE] - "
labels: [enhancement]
assignees:
  - koydas

body:
  - type: markdown
    attributes:
      value: |
        Please describe your proposal clearly 🙌

  - type: input
    id: context
    attributes:
      label: Context
      description: Why is this feature needed?
      placeholder: e.g. To improve the user experience...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Describe the feature and its expected behavior
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Considered alternatives
      placeholder: Are there other ways to solve this need?
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact level
      description: Importance or urgency of the feature
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false
